name: Publish Docker image

on:
  push:
    branches:
      - master

jobs:
  Deploy-to-production:
    runs-on: ubuntu-latest
    if: github.ref_name == 'master'
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.USERNAME_DOCKER }}
          password: ${{ secrets.PASSWORD_DOCKER }}
      - name: Build and push Docker Image
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: pcoker581/service-erp:production
      - name: Pull Docker Image In Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOSTNAME }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            docker pull pcoker581/service-erp:production
            cd ~/erp
            docker-compose down
            docker-compose up -d
